name: Integração continua de Java com Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    name: build-dev - Compilação e teste
    steps:
    - name: Configura xvfb para tela 0
      run: Xvfb :1 -screen 0 1600x1200x24 &    
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    - name: Configura o JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Compila o projeto com Maven
      run: mvn -B test --file pom.xml
      env:
        DISPLAY: :1
    - name: Desliga Xvfb
      run: killall Xvfb    

  build-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
    needs: build-dev
    name: build-hmg - Análise do código
    steps:
    - name: Configura xvfb para tela 0
      run: Xvfb :1 -screen 0 1600x1200x24 &    
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0 
    - name: Configura o JDK 18
      uses: actions/setup-java@v3      
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven     
    - name: Cache dos pacotes do SonarCloud
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache dos pacotes do Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Verifica o projeto com Maven e Jacoco
      run: |
        mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=IanAkira_CadastroClienteDesktop \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        DISPLAY: :1
    - name: Desliga Xvfb
      run: killall Xvfb  

  build-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
    needs: build-hmg
    name: build-prd - Empacotamento
    steps:
    - name: Configura xvfb para tela 0
      run: Xvfb :1 -screen 0 1600x1200
